name: CI Pipeline Canvas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - 
      name: Install dependencies
      run: dotnet restore
    - 
      name: Build
      run: dotnet build --no-restore
    - 
      name: Test
      run: dotnet test
      
    - 
      name: publish
      working-directory: CanvasRabbitMQSender
      run: dotnet publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    -
      name: Create VPN connection
      shell: pwsh
      env:
        USER: ${{ secrets.EHB_USER}}
        SECRET: ${{ secrets.EHB_PASSWORD}}
      run: | 
       Add-VpnConnection -Name "EHB_VPN" -ServerAddress "dtsslvpn.ehb.be" -TunnelType "SSTP" -AllUserConnection -Force
       rasdial "EHB_VPN" "$env:USER" "$env:SECRET"
       
    - name: publish
      working-directory: CanvasRabbitMQSender
      run: dotnet publish
       
    - name: FTP Deploy
        #You may pin to the exact commit or the version.
        #uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with: 
        server: 10.3.17.67
        username: ftpuser
        password: ubuntu123
        port: 21
        local-dir: /home/runner/work/Canvas/Canvas/CanvasRabittMQSender/deploy/
        server-dir: /home/ftpuser/ftp/files/

   # - name: git-ftp-action
  # You may pin to the exact commit or the version.
  # uses: sebastianpopp/git-ftp-action@33a94c0e0fce59ca477baa9d1748a5f2e53fb429
     # uses: sebastianpopp/git-ftp-action@3.0.0
     # with:
    # URL
       # url: ftp://10.3.17.67
    # FTP login name
       # user: ftpuser
    # FTP password
       # password: ubuntu123
    # Specifies a local directory to sync from as if it were the git project root path.
       # syncroot: /home/ftpuser/ftp/files
    
       
       
    #- name: ls -a via OPEN SSH Private Key
      #uses: garygrossgarten/github-action-ssh@release
      #with:
        #command: ls -a
        #host: 10.3.17.67
        #username: canvas
        #passphrase: ${{ secrets.VM_PASSWORD }}
      #env:
       # CI: true
   # - 
     # name: Run SSH command
     # uses: garygrossgarten/github-action-ssh@release
      #with:
       # command: sudo service CanvasRabitMQSender start
        #host: 10.3.17.67
        #username: canvas
        #passphrase: ${{ secrets.VM_PASSWORD }}
