name: CI Pipeline Canvas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy and test ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 10.3.17.67
        username: canvas
        #password: sdf765SDF
        key: ${{secrets.canvas_private_key}}
        port: 22
        #passphrase: ${{secrets.passphrase_private_key}}
        #description: passphrase is used for encrypt the data between two points.
        #args: "-tt"
        debug: true
        script: |
          cd CanvasApp
          git pull origin master
          git status
          
    
      

