name: CI Pipeline Canvas
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - 
      name: Install dependencies
      run: dotnet restore
    - 
      name: Build
      run: dotnet build --no-restore
    - 
      name: Test
      run: dotnet test
      
    - 
      name: publish
      working-directory: CanvasRabbitMQSender
      run: dotnet publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    -
      name: Create VPN connection
      shell: pwsh
      env:
        USER: ${{ secrets.EHB_USER}}
        SECRET: ${{ secrets.EHB_PASSWORD}}
      run: | 
       Add-VpnConnection -Name "EHB_VPN" -ServerAddress "dtsslvpn.ehb.be" -TunnelType "SSTP" -AllUserConnection -Force
       rasdial "EHB_VPN" "$env:USER" "$env:SECRET"
    -
      name: start VPN connection
      shell: pwsh
      env:
        USER: ${{ secrets.EHB_USER}}
        SECRET: ${{ secrets.EHB_PASSWORD}}
      run: | 
        Get-VpnConnection -Name "EHB_VPN"
       

    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        command: sudo service CanvasRabitMQSender start
        host: 10.3.17.67
        username: canvas
        passphrase: ${{ secrets.VM_PASSWORD }}
